### ISSUE TITLE
.dat file reading error

### ISSUE THREAD

**Issue by esravar** [siqueira-hc/Efficient-Facial-Feature-Learning-with-Wide-Ensemble-based-Convolutional-Neural-Networks#2]
Hi,
When I run "python main_esr9.py video -i ./media/big_bang.mp4 -d -f 5 -s 2", it gives this error: Unable to open ./model/utils/templates/dlib/cnn-face-detector.dat for reading.

How can I solve this??

**Comment by siqueira-hc** [comment]
Hello Esravar,

I tried to reproduce the error in different computers but the error was not raised.

Please, double-check if the file cnn_face_detector.dat exists and is located at "[folder of the framework]/model/utils/templates/dlib/".

The error is related to the Dlib framework. You could try to create a new environment and re-install Dlib.

What is your OS?

Currently, the Facial Expression Recognition Framework works on Linux.

Best,
Henrique

**Comment by esravar** [comment]
Ok, I'm working on windows and I fixed the error. Thanks for your reply:)
